services:
  web:
    build: ./web
    container_name: space-engineers-web
    ports:
      - "80:80"
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  se-server:
    image: mmmaxwwwell/space-engineers-dedicated-docker-linux:latest
    container_name: space-engineers-dedicated-docker-linux
    restart: unless-stopped
    volumes:
      - ./server/appdata/space-engineers/config/World:/appdata/space-engineers/World
      - ./server/appdata/space-engineers/config/Plugins:/appdata/space-engineers/Plugins
      - ./server/appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
      - ./server/appdata/space-engineers/bins/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ./server/appdata/space-engineers/bins/steamcmd:/home/wine/.steam
    ports:
     - "27016:27016/udp"
